[package]
name = "route-recognizer"
description = "Recognizes URL patterns with support for dynamic and glob segments"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustasync/route-recognizer"
keywords = ["router", "url"]

version = "0.1.13"
authors = ["wycats"]
